SELECT 
S.USERNAME,
O.OBJECT_NAME,
o.object_id,
o.subobject_name,
L.LOCKED_MODE,
S.SID,
S.SERIAL#,
ROW_WAIT_OBJ#,
ROW_WAIT_FILE#,
ROW_WAIT_BLOCK#,
ROW_WAIT_ROW#,
P.SPID,
S.PROGRAM,
l.process,
S.MACHINE
FROM V$LOCKED_OBJECT L,
all_OBJECTS O,
V$SESSION S,
V$PROCESS P
WHERE L.OBJECT_ID = O.OBJECT_ID
AND L.SESSION_ID  = S.SID
AND S.PADDR       = P.ADDR;